# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files


-   repo: https://github.com/PyCQA/pylint
    rev: v2.15.5
    hooks:
    -   id: pylint
        language: system
        args:
        - --output-format=colorized
        - --errors-only
        - --ignore-paths=[tests/]

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
