name: Pytest

on:
  push:
    branches:
      - pytest

  workflow_dispatch:

jobs:
  pytest-install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Install dependencies
        run: |
          pip install pytest
          pip install -r requirements.txt
      
      - name: Test with pytest
        run: |
          pytest
   
