name: Pytest

on:
  push:
    branches:
      - pytest

  workflow_dispatch:

jobs:
  pytest-install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

   
